### ISSUE TITLE
incompatible numbers of dimensions

### ISSUE THREAD

**Issue by ebrahimebrahim** [HastingsGreer/ConstrICON_multichannel_train#1]
I got the following when trying this out on a pair of training images:

```txt
Traceback (most recent call last):
  File "/home/ebrahimebrahim/Desktop/trying_out_hastings_model/ConstrICON_multichannel_train/.venv/lib/python3.8/site-packages/itk/support/template_class.py", line 525, in __getitem__
    this_item = self.__template__[key]
KeyError: (<class 'itk.itkImagePython.itkImageF4'>, <class 'itk.itkImagePython.itkImageF3'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 62, in <module>
    phi_AB, phi_BA = icon_registration.itk_wrapper.register_pair(net,preprocess(moving), preprocess(fixed), finetune_steps=50)
  File "cli.py", line 40, in preprocess
    image = itk.CastImageFilter[type(image), itk.Image[itk.F, 3]].New()(image)
  File "/home/ebrahimebrahim/Desktop/trying_out_hastings_model/ConstrICON_multichannel_train/.venv/lib/python3.8/site-packages/itk/support/template_class.py", line 529, in __getitem__
    raise itk.TemplateTypeError(self, key)
itk.support.extras.TemplateTypeError: itk.CastImageFilter is not wrapped for input type `itk.Image[itk.F,4], itk.Image[itk.F,3]`.

(...)
```

It seemed like the 3 should be a 4 [here](https://github.com/HastingsGreer/ConstrICON_multichannel_train/blob/cfe394cc4b6d4f31afd3ae354cbc82300c081912/cli.py#L40). After that change there is another issue:

```
Traceback (most recent call last):
  File "cli.py", line 64, in <module>
    phi_AB, phi_BA = icon_registration.itk_wrapper.register_pair(net,preprocess(moving), preprocess(fixed), finetune_steps=50)
  File "/home/ebrahimebrahim/Desktop/trying_out_hastings_model/ConstrICON_multichannel_train/.venv/lib/python3.8/site-packages/icon_registration/itk_wrapper.py", line 51, in register_pair
    A_resized = F.interpolate(
  File "/home/ebrahimebrahim/Desktop/trying_out_hastings_model/ConstrICON_multichannel_train/.venv/lib/python3.8/site-packages/torch/nn/functional.py", line 3934, in interpolate
    raise ValueError(
ValueError: Input and output must have the same number of spatial dimensions, but got input with spatial dimensions of [4, 140, 140, 140] and output size of torch.Size([140, 140, 140]). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.
```

What am I missing here?

**Comment by HastingsGreer** [comment]
That's a great question, let me make sure my local code is synchronized with the repo

**Comment by HastingsGreer** [comment]
Ok, I think everything is sorted out now. The multichannel brain images in this dataset are being stored as 4d images, not 3d images with vector valued pixels. This means that they've got 4-D orientation and spacing (apparently different polynomial coefficients are separated by 4.2 mm haha.) I added some assumptions about how to turn a 4-d spacing into a 3-d spacing that seem pretty reasonable (the spacings before and after are printed, and the processed images saved to disk, with the flag --spacing_debug) but my assumptions don't seem to match slicer's, which we can dig into later.

https://github.com/HastingsGreer/ConstrICON_multichannel_train/tree/76aacee0858ae3721840334763022a2eb71d516c

**Comment by ebrahimebrahim** [comment]
It works! Output visually looks good in Slicer. We'll see how it scores on tract alignment
It generates the transform only and doesn't seem to save the warped moving image.
(But the warped moving image isn't important for us anyway.)
Thanks!

> apparently different polynomial coefficients are separated by 4.2 mm haha

(haha)
